# Default values for opentelemetry-collector.
image:
  repository: otel/opentelemetry-collector
  tag: 0.86.0
  pullPolicy: IfNotPresent

mode: deployment # Can be deployment, daemonset, or statefulset

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 8888
      targetPort: 8888
    - name: jaeger-thrift
      port: 14268
      targetPort: 14268
    - name: zipkin
      port: 9411
      targetPort: 9411

config:
  exporters:
    logging:
      loglevel: info
    prometheus:
      endpoint: "0.0.0.0:8889"
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    jaeger:
      protocols:
        thrift_http:
    zipkin: {}
  service:
    pipelines:
      traces:
        receivers: [otlp, jaeger, zipkin]
        processors: []
        exporters: [logging]
      metrics:
        receivers: [otlp]
        processors: []
        exporters: [logging, prometheus]
      logs:
        receivers: [otlp]
        processors: []
        exporters: [logging]

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: false
  minAvailable: 1

grafana:
  enabled: true
  adminPassword: admin
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      otel-collector-dashboard:
        gnetId: 12559
        revision: 1
        datasource: Prometheus
