apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opentelemetrycollectors.opentelemetry.io
spec:
  group: opentelemetry.io
  names:
    kind: OpenTelemetryCollector
    listKind: OpenTelemetryCollectorList
    plural: opentelemetrycollectors
    singular: opentelemetrycollector
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                mode:
                  type: string
                  enum: [deployment, daemonset, statefulset, sidecar]
                image:
                  type: string
                config:
                  type: string
                serviceAccount:
                  type: string
                volumeMounts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mountPath:
                        type: string
                      readOnly:
                        type: boolean
                volumes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      configMap:
                        type: object
                        properties:
                          name:
                            type: string
                      secret:
                        type: object
                        properties:
                          secretName:
                            type: string
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
                affinity:
                  type: object
                tolerations:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      value:
                        type: string
                      effect:
                        type: string
      subresources:
        status: {}
